trackings_to_ignore = [
'Aguarda transbordo',
'Ajuda com internet - validações',
'Apresentação nina',
'Aviso email',
'Aviso suspenso',
'Aviso throttling',
'Central ajuda',
'Consulta plano / consumo',
'Código / email',
'Elegivel religue',
'Email fatura nao enviado',
'Email fatura nao enviado - digitada',
'Enviou email',
'Erro genérico',
'Exceptions',
'Falha servico',
'Finalizacao - opcao',
'Fora do Horario de atendimento - Usuarios',
'Funcionalidade',
'Gerou código',
'Informar pagto',
'Input handler - 1',
'Input handler - 2',
'Menos de 3',
'Mensagem nao entendida atendimento',
'Menu principal',
'Menu religue',
'Menu suspenso',
'Nextel',
'Não elegível',
'Não tem email',
'Não tem fatura',
'Pede email',
'Perfil de usuario',
'Pj',
'Prospect',
'Reativação',
'Redireciona para lojas',
'Religou',
'Requestcustomerinfo',
'Requestduedate Requestebill - get',
'Requestebill - post',
'Requestelegibility',
'Requestemail',
'Requestfranchise',
'Requestfreemode get',
'Requestfreemode put',
'Requestplan',
'Requestprotocol',
'Requestra',
'Requestreactivation',
'Requestsendslip',
'Requestsliplist',
'Ret religue',
'Roteador customer info',
'Roteador dev',
'Roteador encontrou cadastro',
'Roteador erro',
'Roteador erro + textao',
'Roteador intencao',
'Roteador intencao + 1 x entidade',
'Roteador intencao + 2 x entidade',
'Roteador negativo/positivo',
'Roteador nlp',
'Roteador protocol',
'Roteador texticulo',
'Sem problemas',
'Start',
'Suspenso',
'Tem fatura',
'Texto input - caracteres',
'Texticulo input - caracteres',
'Valida protocolo',
'Validacao ath no periodo de recencia',
'Validacao cadastro fatura digital',
'Validacao email existente',
'Validacao fatura aberta ou boleto negociado',
'Validacao identificacao numero',
'Validacao linha suspensa',
'Validacao numero nextel',
'Validacao numero no formato',
'Validacao numero prospect',
'Validacao pcl linha suspensa',
'Validacao reativacao confianca',
'Validaemail',
'Vocaliza franquia e consumo',
'flow' ]