import urllib.parse
from blip_report_requisitor import Requisitor
import json

class Trackings:
    def __init__(self):
        bot_credentials = json.load(open('credentials/bot.json', 'r'))
        self.requisitor = Requisitor(bot_credentials['key'])
    
    def get_all(self):
        return ['Nao nextel',
            ' saudação',
            'Falha no servico',
            'Linha pj',
            'Linha happy',
            'Linha pre pago',
            'Menu linha ativa',
            'Menu linha suspensa',
            'Nina',
            'Sem fatura aberta',
            'Menos de 3 faturas',
            'Mais de 3 faturas',
            'Email nao cadastrado',
            'Email cadastrado',
            'Codigo de barras gerado',
            'Email certo',
            'Reconfirmacao de email',
            'Email fatura nao enviado',
            'Email fatura enviado',
            'Informar pagamento',
            'Pagamento mais 3 dias',
            'Pagamento menos 3 dias',
            'Negociar valores - sem debito',
            'Reativacao recente',
            'Reativacao - pagamento em aberto',
            'Reativacao - pedido solicitado',
            'Menu generico linha ativa',
            'Menu generico linha suspensa',
            'Menu retorno',
            'Menu retorno linha ativa',
            'Menu retorno linha suspensa',
            'Protocolo',
            'Erro vídeo',
            'Erro imagem',
            'Erro persistente',
            'Bad talk',
            'Agradecimento',
            'Cliente nextel',
            'Fatura',
            'Requestsliplist',
            'Requestemail',
            'Requestsendslip',
            'Roteador erro + textao',
            'Reconhecida com resposta',
            'Roteador intencao + 2 x entidade',
            'Interacao numero prospect',
            'Pede numero',
            'Codigo de barras nao gerado',
            'Codigo de barras gerado email cadastrado',
            'Ja conhece fatura eletronica',
            'Nao conhece fatura eletronica',
            'Fatura digital',
            'Fatura digital ativa',
            'Ajuda com internet',
            'Linha suspensa',
            'Linha throtlling',
            'Desativar velocidade reduzida',
            'Nao desativar',
            'Linha freemode',
            'Velocidade reduzida desativada',
            'Consulta dados realizada',
            'Encerrou',
            'Principal',
            'Roteador protocol',
            'Smalltalks integration',
            'Boa tarde',
            'Bom dia',
            'Boa noite',
            'Não cliente handler',
            'Sem portabilidade input',
            'Com portabilidade input',
            'Persistencia sem input',
            'Sem portabilidade',
            'Com portabilidade',
            'Elogio',
            'Segunda via acordo',
            'Configurar linha',
            'Configurar sms',
            'Configurar apn',
            'Cancelamento',
            'Mudar email',
            'Meu nextel',
            'Mudar endereco',
            'Mudar plano',
            'Portabilidade',
            'Roaming',
            'Finalizacao - protocolo',
            'Intencao falar com atendente',
            'Data de vencimento',
            'Mudar endereco e email',
            'Textao',
            'Textao - recorrente',
            'Despedida',
            'Texticulo',
            'Texticulo 2a interacao',
            'Roteador negativo/positivo',
            'Feedback',
            'Feedback anotado',
            'Feedback negativo',
            'Feedback negativo',
            'Feedback anotado',
            'Feedback positivo',
            'Segunda via acordo',
            'Contestar fatura',
            'Pdf',
            'Teste ajuda com internet',
            'Bloquear',
            'Desbloquear',
            'Desbloqueio chip',
            'Solicitar chip',
            'Solicitar linha',
            'Reclamacao',
            'Perda e roubo',
            'Bloqueio',
            'Bloqueio chip',
            'Problema com chip',
            'Problema com linha',
            'Problema com chip input',
            'Taxa',
            'Taxa o que e',
            'Taxa qual valor',
            'Taxa boleto',
            'Taxa pagamento',
            'Contestação não disponível',
            'Humano',
            'Espera do transbordo',
            'Não é alto valor',
            'Após atendimento',
            'Fora de horario de atendimento',
            'Redireciona para lojas',
            'Erro de transbordo',
            'Erro generico',
            'Erro desativacao freemode',
            'Erro reativacao',
            'Erro cadastramento fd',
            'Erro de input de e-mail',
            'Erro envio fatura',
            'Erro condigo de barras',
            'Erro generico começo',
            'Erro arquivo',
            'Erro falha generico',
            'Erro audio',
            'Reajuste',
            'Finalizacao - nao resolveu',
            'Numero nao nextel',
            'Numero nao identificado',
            'Erro confirmacao cliente',
            'Numero fora do formato',
            'Codigo sms',
            'Codigo sms invalido',
            'Codigo sms valido',
            'Erro numero invalido',
            'Finalizacao',
            'Protocolo',
            'Nao nextel',
            'Reativacao - pagamento realizado',
            'Reativar',
            'Erro persistente feedback inativo',
            'Erro persistente transbordo no horario',
            'Fila de espera',
            'Espera atendimento',
            'Nao espera atendimento',
            'Mensagem nao entendida atendimento',
            '#resquestqueue',
            'Erro consulta do plano',
            'Mudar plano minutos ilimitados',
            'Melhor oferta plano',
            'Recusa melhor oferta plano',
            'Alteracao plano',
            'Plano alterado',
            'Falha alteracao de plano',
            'Mudar plano reativacao',
            'Mudar plano elegivel reativacao',
            'Transbordo desligado',
            'Menu outros assuntos',
            'Intencao nao reconhecida outros assuntos',
            'Link problema tecnico expirado',
            'Transbordo problema tecnico desabilitado',
            'Transbordo problema tecnico',
            'Validacao pcl linha suspensa',
            'Numero in fraude',
            'Pcl linha suspensa',
            'Pcl solicitou cancelamento',
            'Refresh',
            'Refresh mesmo assunto',
            'Refresh outro assunto',
            'Testar internet delay',
            'Testar internet concluido',
            'Testar internet falha',
            'Testar internet aguardando',
            'Validacao ath no periodo de recencia',
            'Ath fora da recencia',
            'Ath dentro da recencia',
            'Troca de plano link expirado',
            'Troca de plano servico inativo',
            'Troca de plano servico ativo',
            'Validacao boleto negociado funcionalidade habilitada',
            'Validacao fatura aberta ou boleto negociado',
            'Fatura eletronica nao cadastrada',
            'Email invalido']
        return self.requisitor.getAllTrackingCategories()

    def get_value(self, name, begin_date, end_date):
        url = f"/event-track/{urllib.parse.quote(name)}"
        return self.requisitor.getCustomReport(url, begin_date, end_date)
